version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: processes-stamp
    container_name: processes-stamp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
